# Generated by Django 5.1.7 on 2025-03-24 00:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth"."users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='posts.user')),
            ],
            options={
                'db_table': 'tweet"."tweet',
            },
        ),
        migrations.CreateModel(
            name='Retweet',
            fields=[
                ('retweet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to='posts.tweet')),
            ],
            options={
                'db_table': 'tweet"."retweet',
            },
        ),
    ]
